'use client'

import React from 'react';
import "./globals.css";
import { GlobalStyle } from "@/styles/globalStyles";
import { ThemeProvider } from "styled-components";
import theme from "@/styles/theme";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { createNetworkConfig, IotaClientProvider, WalletProvider } from '@iota/dapp-kit';
import { getFullnodeUrl, Network } from '@iota/iota-sdk/client';

import Layout from '@/components/Layout';
import Header from '@/components/Header';
import HeaderContent from '@/components/HeaderContent';
import Main from '@/components/Main';
import GridContainer from '@/components/GridContainer';
import MainContent from '@/components/MainContent';
import ProgressBar from '@/components/ProgressBar';
import SlideCounter from '@/components/SlideCounter';
import NavigationButtons from '@/components/NavigationButtons';
import NavigationHint from '@/components/NavigationHint';

// Required to give sytle to UI components imported from dapp-kit such as ConnectButton
import '@iota/dapp-kit/dist/index.css'

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// <ThemeProvider theme={theme}>
//   {/* This provider casts theme properties to all components down the tree. */}
//   <html lang="en">
//     <body>
//       {/* Introduces a global style in the html page rendered with this component. */}
//       <GlobalStyle />
//       <div className="flex flex-col min-h-screen">
//         <LayoutHeader />
//         <main className="flex-1 p-3 overflow-hidden">
//           {children}
//         </main>
//         <LayoutFooter />
//       </div>
//     </body>
//   </html>
// </ThemeProvider>

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [currentSlide, setCurrentSlide] = React.useState(1);
  const [totalSlides] = React.useState(10);

  // Why do I need to create an instance of it for each component rendering?
  const queryClient = new QueryClient();

  // Why do I need to create an instance of it for each component rendering?
  const { networkConfig } = createNetworkConfig({
    // getFullnodeUrl do not support network auto-completion
    //   I've had to read getFullnodeUrl file definition to find Network enum.
    //   Therefore, I believe this can be improved to allow auto-completion and
    //   increase developer experience.
    // It may also worth a contribution to change the README.md file of dapp-kit
    //   to enforce the usage of Network enum in the sample in place of hardcoded
    //   value 'mainnet'.
    testnet: { url: getFullnodeUrl(Network.Testnet) },
    mainnet: { url: getFullnodeUrl(Network.Mainnet) }
  });

  const handlePrevious = () => {
    if (currentSlide > 1) {
      setCurrentSlide(prev => prev - 1);
    }
  };

  const handleNext = () => {
    if (currentSlide < totalSlides) {
      setCurrentSlide(prev => prev + 1);
    }
  };

  const canGoPrevious = currentSlide > 1;
  const canGoNext = currentSlide < totalSlides;
  const progress = (currentSlide / totalSlides) * 100;

  return (

    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <IotaClientProvider networks={networkConfig} defaultNetwork='testnet'>
            <WalletProvider>
              <Layout>
                {children}
              </Layout>
              {/* Portal target for modals */}
              <div id="modal-root" />
            </WalletProvider>
          </IotaClientProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
