# PHASE 1 - Build
FROM rust:1.85 AS builder

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    ca-certificates \
    clang-14 \
    libclang-14-dev \
    build-essential \
    cmake \
    git \
    && rm -rf /var/lib/apt/lists/*

ENV LIBCLANG_PATH=/usr/lib/llvm-14/lib

WORKDIR /usr/src/app

COPY Cargo.toml Cargo.lock ./

COPY src ./src
COPY ith ./ith

RUN cargo build --release


# PHASE 2 - Runtime
FROM iotaledger/iota-tools:v0.11.4-rc

RUN apt-get update && apt-get install -y \
    libssl-dev \
    ca-certificates \
    libstdc++6 \
    libclang1-14 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /usr/src/app/target/release/main ./main
COPY --from=builder /usr/src/app/target/release/import_accounts ./import_accounts

ARG ITH_PKG_ID
ARG API_KEY
ARG TCP_LISTNER
ARG ROOT_AUTH_SECRET_KEY
ARG MANUFACTURER_SECRET_KEY
ARG IOTA_IDENTITY_PKG_ID

ENV ITH_PKG_ID=$ITH_PKG_ID
ENV API_KEY=$API_KEY
ENV TCP_LISTNER=$TCP_LISTNER
ENV ROOT_AUTH_SECRET_KEY=$ROOT_AUTH_SECRET_KEY
ENV MANUFACTURER_SECRET_KEY=$MANUFACTURER_SECRET_KEY
ENV IOTA_IDENTITY_PKG_ID=$IOTA_IDENTITY_PKG_ID

CMD sh -c './import_accounts && exec ./main'

EXPOSE 3001
